version: '3'

services:
  master:
    build: ./jenkins-master/
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home/
      - jenkins-log:/var/log/jenkins/
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    networks:
      - jenkins-net

        #  nginx:
        #    build: ./jenkins-nginx/
        # ports:
        #- "8080:80"
        #networks:
        # - jenkins-net
  

volumes:
  jenkins-data:
  jenkins-log:

networks:
  jenkins-net:
